name: Ada (GNAT)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain and dependencies
      run: >
        sudo apt-get update && 
        sudo apt-get install gnat gprbuild libcsfml-dev libglu1-mesa-dev

    - name: Build
      run: gprbuild -j0 -p asfml.gpr

    - name: Build tests
      run: >
        cd tests &&
        for dir in clock example music opengl renderwindow thread window; do
          cd $dir &&
          gprbuild -j0 -p main.gpr &&
          cd - ;
        done
