name: Ada (GNAT)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: alire-project/setup-alire@v1

    - name: Build
      run: alr build

    - name: Build tests
      run: >
        cd tests &&
        for dir in clock example music opengl renderwindow thread window; do
          cd $dir &&
          alr exec -- gprbuild -j0 -p main.gpr &&
          cd - ;
        done
